--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/30/2018 11:40:31 PM
-- Server version: 5.5.5-10.1.37-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS db_nhaconline;

CREATE DATABASE IF NOT EXISTS db_nhaconline
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

--
-- Set default database
--
USE db_nhaconline;

--
-- Create table `album`
--
CREATE TABLE IF NOT EXISTS album (
  id int(100) NOT NULL AUTO_INCREMENT,
  tenalbum varchar(100) NOT NULL,
  image varchar(100) NOT NULL,
  casi varchar(100) DEFAULT NULL,
  chude varchar(100) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `chude`
--
CREATE TABLE IF NOT EXISTS chude (
  id int(100) NOT NULL AUTO_INCREMENT,
  tenchude varchar(100) NOT NULL,
  image varchar(100) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `casi`
--
CREATE TABLE IF NOT EXISTS casi (
  id int(100) NOT NULL AUTO_INCREMENT,
  tencasi varchar(100) NOT NULL,
  image varchar(100) NOT NULL,
  tieusu text DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `baihat`
--
CREATE TABLE IF NOT EXISTS baihat (
  id int(100) NOT NULL AUTO_INCREMENT,
  tenbaihat varchar(100) NOT NULL,
  path varchar(100) NOT NULL,
  image varchar(100) NOT NULL,
  luotnghe int(100) NOT NULL,
  idalbum int(10) NOT NULL,
  idcasi int(10) NOT NULL,
  idchude int(10) NOT NULL,
  ngaydang datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE baihat
ADD CONSTRAINT baihat_ibfk_1 FOREIGN KEY (idcasi)
REFERENCES casi (id);

--
-- Create foreign key
--
ALTER TABLE baihat
ADD CONSTRAINT baihat_ibfk_2 FOREIGN KEY (idchude)
REFERENCES chude (id);

--
-- Create foreign key
--
ALTER TABLE baihat
ADD CONSTRAINT baihat_ibfk_3 FOREIGN KEY (idalbum)
REFERENCES album (id);

--
-- Create view `v_baihat`
--
CREATE
DEFINER = 'root'@'localhost'
VIEW IF NOT EXISTS v_baihat
AS
SELECT
  `bh`.`id` AS `id`,
  `bh`.`tenbaihat` AS `tenbaihat`,
  `bh`.`path` AS `path`,
  `bh`.`image` AS `image`,
  `bh`.`luotnghe` AS `luotnghe`,
  `cs`.`tencasi` AS `tencasi`,
  `ab`.`tenalbum` AS `tenalbum`,
  `cd`.`tenchude` AS `tenchude`,
  `bh`.`ngaydang` AS `ngaydang`,
  `bh`.`idchude` AS `idchude`,
  `bh`.`idcasi` AS `idcasi`,
  `bh`.`idalbum` AS `idalbum`
FROM (((`baihat` `bh`
  JOIN `casi` `cs`
    ON ((`bh`.`idcasi` = `cs`.`id`)))
  JOIN `chude` `cd`
    ON ((`bh`.`idchude` = `cd`.`id`)))
  JOIN `album` `ab`
    ON ((`bh`.`idalbum` = `ab`.`id`)));

--
-- Create table `user`
--
CREATE TABLE IF NOT EXISTS user (
  id int(255) NOT NULL AUTO_INCREMENT,
  userName varchar(100) NOT NULL,
  passWord varchar(100) NOT NULL,
  hoten varchar(200) DEFAULT NULL,
  gioitinh varchar(100) DEFAULT NULL,
  ngaysinh varchar(100) DEFAULT NULL,
  diachi varchar(100) DEFAULT NULL,
  sdt varchar(20) DEFAULT NULL,
  email varchar(100) NOT NULL,
  level int(1) NOT NULL DEFAULT 0,
  code varchar(100) NOT NULL,
  active int(1) DEFAULT NULL,
  avatar varchar(100) NOT NULL DEFAULT 'image/avatar.png',
  ngaydangky datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create table `comment`
--
CREATE TABLE IF NOT EXISTS comment (
  id int(100) NOT NULL AUTO_INCREMENT,
  noidung text DEFAULT NULL,
  thoigian datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  duyet int(1) NOT NULL DEFAULT 0,
  iduser int(100) NOT NULL,
  idbaihat int(100) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 14,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_unicode_ci;

--
-- Create foreign key
--
ALTER TABLE comment
ADD CONSTRAINT comment_ibfk_1 FOREIGN KEY (iduser)
REFERENCES user (id);

--
-- Create foreign key
--
ALTER TABLE comment
ADD CONSTRAINT comment_ibfk_2 FOREIGN KEY (idbaihat)
REFERENCES baihat (id);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;